import math, struct, os, re, sys, csv, itertools, time
from operator import itemgetter


class TUBE:

    ############################################################################## TUBE GENERATING METHOD ###
    #
    # 1. method: Tubes can be generated by two different methods, 'degenerate' or 'combinatorial'.
    # 2. restrict_tube_size: Tubes can be restricted by the number amino acids encoded. The
    #     default value is 50 for degenerate method and 3 for combinatorial method.
    # 3. avoid_aa: Tubes containing specified amino acids are removed. Eg: avoid_aa=['P','C']
    # 4. avoid_stop_codon: If True (default), tubes encoding for stop codon are removed.
    # 5. junk_percent: Enter percentage of allowed junk (default: 0.34). Junk is non-desired amino acids
    #     in a tube encoded due to degeneracy and are calculated wrt overall tube size.
    # 6. junk_type: pecifies whether junk should be 'deimmunizing' (default) or 'nondeimmunizing'.
    #
    ####################### Default Tube generation parameters
    def generate_tube(self, method='degenerate', restrict_tube_size=50, avoid_aa=[], avoid_stop_codon=True, junk_percent=0.34, junk_type='deimmunizing'):
        self.initialize_score_potential()
        if os.path.splitext(self.score_potential)[1] in [".csv", ".CSV"]:
            self.load_csv_score_potential()
        else: self.load_binary_score_potential()
        self.initialize_tube()
        self.thresholdFilter(0, 20, filter=False)
        self.tube_aa_deimmunizing(self.minEpiDel, 0, self.episcore_threshold)
        self.generateTubes(method, restrict_tube_size, avoid_aa, avoid_stop_codon, junk_percent, junk_type)
        self.renameTubes()
        
        res_pos = self.selected_tubes.keys()
        res_pos.sort()
        if self.possible_choices is not None:
            with open(self.possible_choices, "wb") as choice_file:
                choice_file_writer = csv.writer(choice_file)
                for pos in res_pos:
                    for tube in self.selected_tubes[pos]:
                        row = [pos+1, tube]
                        choice_file_writer.writerow(row)
            sys.stdout.write("\nTube choices are is saved in \"%s\".\n\n"%self.possible_choices)

    def generate_tube_potential(self): 
        self.onebody_tube()
        self.twobody_tube()
        self.onebody_score = self.onebody_tubescores
        self.twobody_score = self.twobody_tubescores
        res_pos = self.selected_tubes.keys()
        res_pos.sort()
        if self.tube_score_potential is not None:
            with open(self.tube_score_potential, "wb") as score_potential_file:
                score_potential_file_writer = csv.writer(score_potential_file)
                # score potential starts from 0. This make residues start at 1
                for p in res_pos:
                    pos = p + 1
                    for tube  in self.selected_tubes[p]:
                        onebody_key = (p, tube, 0)
                        if onebody_key in self.onebody_score: 
                            score_key = self.onebody_score[onebody_key]
                        else:
                            score_key = self.penalty
                        line = [pos, tube, score_key, '', '']
                        score_potential_file_writer.writerow(line)
                for p1 in range(len(res_pos)-1):
                    pos1 = res_pos[p1] + 1
                    for aa1 in self.selected_tubes[p1]:
                        for p2 in range(p1+1, len(res_pos)):
                            pos2 = res_pos[p2] + 1
                            for aa2 in self.selected_tubes[p2]:
                                twobody_key = (p1, aa1, 0 , p2, aa2, 0)
                                if twobody_key in self.twobody_score: 
                                    score_key = self.twobody_score[twobody_key]
                                #else:
                                #    score_key = self.penalty
                                #line = [pos1, aa1, pos2, aa2, score_key]
                                #score_potential_file_writer.writerow(line)
                                    line = [pos1, aa1, pos2, aa2, score_key]
                                    score_potential_file_writer.writerow(line)

            sys.stdout.write("Tube score potential is saved in \"%s\".\n\n"%self.tube_score_potential)

    def initialize_tube(self):
        print ('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        print ('            Initializing Tubes                ')
        print ('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        
        self.thres_filtered_seq_choices = []
        self.all_tubes_dict = {} ### <-- This information is passed to scores.py
        self.non_redundant_tubes = {}
        self.tube_group_ratios = {}
        self.nonjunk_tubes = {}
        self.aa_pos_deimm = {}
        self.CDM_tubes = {}
        self.selected_tubes = {}
        
        self.onebody_tubescores = {}
        self.onebody_tube_scoreslist = {}
        self.twobody_tubescores = {}
        self.possible_tubechoices = []
        self.possible_tubepairs = []
        self.AAs = "ACDEFGHIKLMNPQRSTVWY"
        self.CYO_flag = False

        self.AA_possible_choices = []
        for i in self.onebody_score:
            self.AA_possible_choices.append(list(i)[:2])
        self.AA_possible_choices.sort()
        self.tube_dict_generator()

    def tube_dict_generator(self):
        ################## DO NOT EDIT THIS BLOCK ########################################################
        # Degenerate nucleotides:--------------->>>> A,B,C,D,G,H,K,M,N,R,S,T,V,W,Y
        #                                            | | | | | | | | | | | | | | |
        self.dN = [[1,0,0,1,0,1,0,1,1,1,0,0,1,1,0], [0,1,1,0,0,1,0,1,1,0,1,0,1,0,1], [0,1,0,1,1,0,1,0,1,1,1,0,1,0,0], [0,1,0,1,0,1,1,0,1,0,0,1,0,1,1]]
        self.nucleotide = ['a','b','c','d','g','h','k','m','n','r','s','t','v','w','y']
        #
        # codons[base1][base2][base3] = AminoAcid in order, where 0 = A and 21 = Z (stop codon).
        self.codon = [[[8,11,8,11],[16,16,16,16],[14,15,14,15],[7,7,10,7]],[[13,6,13,6],[12,12,12,12],[14,14,14,14],[9,9,9,9]],[[3,2,3,2],[0,0,0,0],[5,5,5,5],[17,17,17,17]],[[21,19,21,19],[15,15,15,15],[21,1,18,1],[9,4,9,4]]]
        #
        self.AA = ['A','C','D','E','F','G','H','I','K','L','M','N','P','Q','R','S','T','V','W','Y','X','Z']
        for dn1 in range(15):
            for dn2 in range(15):
                for dn3 in range(15):
                    for b1 in range(4):
                        if self.dN[b1][dn1] == 1:
                            for b2 in range(4):
                                if self.dN[b2][dn2] == 1:
                                    for b3 in range(4):
                                        if self.dN[b3][dn3] == 1:
                                            nucleotide_key = ''.join([self.nucleotide[dn1], self.nucleotide[dn2], self.nucleotide[dn3]])
                                            if nucleotide_key in self.all_tubes_dict: #if self.all_tubes_dict.has_key(nucleotide_key):
                                                self.all_tubes_dict[nucleotide_key].append(self.AA[self.codon[b1][b2][b3]])
                                            else:
                                                self.all_tubes_dict[nucleotide_key] = [self.AA[self.codon[b1][b2][b3]]]
        #
        ##################################################################################################
    
    



    ############################################################################# THRESHOLD FILTER ###
    #
    # THESE FILTERED AA CHOICES CAN "IMPLICITLY" RESTRICT TUBE SIZE & CHOICES
    # Options for filtering AA seq choices using the criteria of:
    #   1. Conservation score of AA at each position.
    #       Enter 0 for considering all in the list (recommended).
    #       The conservation thres is converted to log and then compared for filtering.
    #       Example: Entering 0.10 conservation threshold would be -log(0.10) = 2.303
    #   2. Fixed number of mutations allowed at each position.
    #       If mutations = 0, then only wildtype is considered.
    #       Or enter mutations=20 to include all possible choices.
    #   3. If filter = False, then nothing is processed. Output choices = Input choices.
    #
    def thresholdFilter(self, cons_thresh=0.00001, mutations=20, filter=False):
        print ('Applying threshold filter on sequences...')
        print (len(self.onebody_score))
        
        if filter==True:
            if cons_thresh == 0: cons_thresh = 0.00001
            cons_thresh = (-1.0) * math.log(cons_thresh)
            
            ################################
            # Conservation threshold allowed mutation filtering
            temp_filtered_choices = []
            for i in range(len(self.AA_possible_choices)):
                if self.onebody_score[tuple(self.AA_possible_choices[i])] <= cons_thresh or self.AA_possible_choices[i][1] == self.wt_seq[self.AA_possible_choices[i][0]]:
                    temp_filtered_choices.append(self.AA_possible_choices[i])

            ################################
            # Filtering based on number of mutations allowed
            #  Iterating each position of the sequence:
            for i in range(len(self.wt_seq)):
                # Non-wildtype residues are assessed and added in decreasing order of their
                #  conservation score; i.e., a choice with a higher conservation score
                #  is given a higher preference.
                temp_dict = {}
                for j in range(len(temp_filtered_choices)):
                    if temp_filtered_choices[j][0] == i and temp_filtered_choices[j][1] != self.wt_seq[i]:
                        temp_dict[(temp_filtered_choices[j][0], temp_filtered_choices[j][1])] = self.onebody_score[tuple(temp_filtered_choices[j])]
                s = list(sorted(temp_dict.items(), key=itemgetter(1)))
                temp_dict.clear()
        
                # Keep adding until number of mutations threshold is reached.
                for m in range(len(s)):
                    if len(temp_dict) >= mutations:
                        break
                    temp_dict[s[m][0]] = s[m][1]
                
                # Also add Wildtype to the above list (always included, no matter what!)
                for j in range(len(temp_filtered_choices)):
                    if temp_filtered_choices[j][0] == i and temp_filtered_choices[j][1] == self.wt_seq[i]:
                        temp_dict[(temp_filtered_choices[j][0], temp_filtered_choices[j][1])] = self.onebody_score[tuple(temp_filtered_choices[j])]

                # This is the final sequence choices list
                for keys in temp_dict.iterkeys():
                    self.thres_filtered_seq_choices.append(list(keys))
            
            self.thres_filtered_seq_choices = map(list, set(map(tuple, self.thres_filtered_seq_choices)))
            self.thres_filtered_seq_choices.sort()
    
        elif filter==False:
            self.thres_filtered_seq_choices = self.AA_possible_choices
        print (self.thres_filtered_seq_choices)
        print ('Total AA thres_filtered_seq_choices: %d' % (len(self.thres_filtered_seq_choices)))




    ############# DO NOT EDIT THE MODULES BELOW ######################################################
    #
    # THESE TWO MODULES ARE USED FOR CONSTRUCTING TUBES USING DIFFERENT METHODS
    #
    def generateTubes(self, method, restrict_tube_size, avoid_aa, avoid_stop_codon, junk_percent, junk_type):
        if restrict_tube_size < 2:
            print ("restrict_tube_size should be 2 or greater")
            sys.exit()
        
        if method == 'degenerate':
            self.generate_degenerate(restrict_tube_size, avoid_aa, avoid_stop_codon, junk_percent, junk_type)
        elif method == 'combinatorial':
            if restrict_tube_size==50: restrict_tube_size=3 # Change default value for combinatorial method to 3
            if restrict_tube_size>10:
                print ("restrict_tube_size should be equal to or less than 10 when used with combinatorial method")
                sys.exit()
            self.generate_combinatorial(restrict_tube_size, avoid_aa, avoid_stop_codon)
        else:
            print ("Enter method='degenerate' or method='combinatorial' as argument. Atleast one is required.")
            print ("You can also restrict tube size, e.g., restrict_tube_size=3")
            sys.exit()


    ################# This module is used to generate tubes using the degenerate method ################
    # DO NOT EDIT THIS MODULE
    def generate_degenerate(self, restrict_tube_size, avoid_aa, avoid_stop_codon, junk_percent, junk_type):
        print ("Generating tubes using degenerate method")
        self.removeRedundant(restrict_tube_size, avoid_aa, avoid_stop_codon)
        self.junkFilter(junk_percent, junk_type)


    ################### This module is used to generate tubes using the combinatorial method ##################
    # DO NOT EDIT THIS MODULE
    def generate_combinatorial(self, restrict_tube_size, avoid_aa, avoid_stop_codon):
        print ("Generating tubes using combinatorial method")
        temp_dict = {}
        #updates
        for f in self.thres_filtered_seq_choices:
            if f[0] in temp_dict:
                temp_dict[f[0]].append(f[1])
            else:
                temp_dict[f[0]] = [f[1]]
        for key, values in temp_dict.iteritems():
            self.nonjunk_tubes[key] = []
            possible_tubes = [c for i in range(len(values)) for c in itertools.combinations(values, i+1)]
            for t in range(len(possible_tubes)):
                if len(possible_tubes[t]) == 1 and possible_tubes[t][0] == self.wt_seq[key]:
                    self.nonjunk_tubes[key].append("".join(possible_tubes[t][0]))
                    self.all_tubes_dict["".join(possible_tubes[t][0])] = list(possible_tubes[t][0])
                    self.tube_group_ratios[key, "".join(possible_tubes[t])] = [0.0]
                elif self.wt_seq[key] in list(possible_tubes[t]) and len(list(possible_tubes[t])) <= restrict_tube_size:
                    self.nonjunk_tubes[key].append("".join(possible_tubes[t]))
                    self.all_tubes_dict["".join(possible_tubes[t])] = list(possible_tubes[t])
                    self.tube_group_ratios[key, "".join(possible_tubes[t])] = [0.0]
        self.non_redundant_tubes = self.all_tubes_dict
        ################################
        # This flag is used to prevent user
        # from accessing junkFilter and removeRedundant
        # modules when using combinatorial method
        self.CYO_flag = True
        ################################
        # Counting selected non-junk tubes
        total_nonjunk_tubes = 0
        for keys, values in self.nonjunk_tubes.iteritems():
            total_nonjunk_tubes += len(values)
        print ('Total nonjunk_tubes: %d' % (total_nonjunk_tubes))
        print (self.nonjunk_tubes)
    #
    ############# DO NOT EDIT THE ABOVE MODULES ######################################################




    ############################################################################## AVOID AA FILTER ###
    #
    # Should be used with degenerate tube method. Tubes are filtered based on the following
    # 1. restrict_tube_size: Tubes can be restricted by the number amino acids encoded. The
    #     default value is 50 for degenerate method and 3 for combinatorial method.
    # 2. avoid_aa: Tubes containing specified amino acids are removed. Eg: avoid_aa=['P','C']
    # 3. avoid_stop_codon: If True (default), tubes encoding for stop codon are removed.
    #
    def removeRedundant(self, restrict_tube_size, avoid_aa, avoid_stop_codon):

        if self.CYO_flag == True:
            print ("removeRedundant() cannot be used with combinatorial method")
            print ("Turn off this module or use degenerate method")
            sys.exit()
        
        ################################
        # add stop codon to the list of avoid_aa
        if avoid_stop_codon==True: avoid_aa = avoid_aa + ['Z']
        print ('Removing redundant tubes...')
        
        ################################
        # avoid AA list 
        for key_1,value_1 in self.all_tubes_dict.iteritems():
            if len(list(set(value_1) & set(avoid_aa))) > 0 and len(value_1) > 1:
                pass
            elif len(value_1) > restrict_tube_size:
                pass
            elif value_1 == ['Z']:
                pass
            else:
                self.non_redundant_tubes[key_1] = value_1
        
        ################################
        # Proportion redundancy check
        temp_dict = {}
        temp_dict['XXX'] = ['B']
        tube_dict = temp_dict.copy()
        for key_1,value_1 in self.non_redundant_tubes.iteritems():
            aa_coded_list_1 = value_1
            redundancy_flag = 0
            for key_2,value_2 in temp_dict.iteritems():
                aa_coded_list_2 = value_2
                if set(aa_coded_list_1) == set(aa_coded_list_2):
                    # they are redundant
                    redundancy_flag = 1
                    size_1 = len(aa_coded_list_1)
                    size_2 = len(aa_coded_list_2)
                    if size_1 > size_2:
                        tube_dict[key_2] = value_2
                        break
                    else:
                        del tube_dict[key_2]
                        tube_dict[key_1] = value_1
                        break
            if redundancy_flag == 0:
                tube_dict[key_1] = value_1
            del temp_dict
            temp_dict = tube_dict.copy()
            
        self.non_redundant_tubes = tube_dict.copy()
        del temp_dict, tube_dict
        del self.non_redundant_tubes['XXX']
        # print 'self.non_redundant_tubes', self.non_redundant_tubes



    ################################################################################### JUNK FILTER #########
    #
    # Should be used degenerate tube method. Tubes are filtered based on the following:
    # 1. junk_percent: Enter percentage of allowed junk (default: 0.34). Junk is non-desired amino acids
    #     in a tube encoded due to degeneracy and are calculated wrt overall tube size.
    # 2. junk_type: pecifies whether junk should be 'deimmunizing' (default) or 'nondeimmunizing'.
    #
    def junkFilter(self, junk_percent, junk_type):
        
        junk = 1 # Junk always allowed
        junk_percent_allowed = junk_percent
        if junk_type=='deimmunizing': deimm_junk = 1
        elif junk_type=='nondeimmunizing': deimm_junk = 0
        else:
            print ("Enter argument junk_type= 'deimmunizing' or 'nondeimmunizing'")
            sys.exit()
    
        if self.CYO_flag == True:
            print ("junk arguments cannot be used with combinatorial method")
            sys.exit()
        
        print ('Applying junk filter...')
        ################################
        # Dictionary keys are positions and values are tubes list
        # Junk filter is applied here
        for i in range(len(self.wt_seq)):
            choice_list = []
            for j in range(len(self.thres_filtered_seq_choices)):
                if self.thres_filtered_seq_choices[j][0] == i:
                    choice_list.append(self.thres_filtered_seq_choices[j][1])
            for keys,values in self.non_redundant_tubes.iteritems():
                degen_list = values
                deimm_flag = 1
                for d in degen_list:
                    if self.aa_pos_deimm[(i, d)]==0 and d is not self.wt_seq[i]: deimm_flag=0
                # If we don't care about deimmunizing junk, then we allow all tubes
                if deimm_junk==0: deimm_flag=1
                if deimm_flag==1:
                    match = 0.0
                    for choice in choice_list:
                        match = match + degen_list.count(choice)

                    if junk == 1 and self.wt_seq[i] in self.non_redundant_tubes[keys]:
                        if (len(degen_list) - match)/(len(degen_list)) <= junk_percent_allowed:
                            self.tube_group_ratios[i, keys] = [(len(degen_list) - match)/(len(degen_list))]
                            if i in self.nonjunk_tubes: 
                                self.nonjunk_tubes[i].append(keys)
                            else:
                                self.nonjunk_tubes[i] = [keys]
                
                    if junk == 0 and self.wt_seq[i] in self.non_redundant_tubes[keys]:
                        if (len(degen_list) - match)/(len(degen_list)) == 0.0:
                            self.tube_group_ratios[i, keys] = [(len(degen_list) - match)/(len(degen_list))]
                            if i in self.nonjunk_tubes: 
                                self.nonjunk_tubes[i].append(keys)
                            else:
                                self.nonjunk_tubes[i] = [keys]
            del choice_list
            
        ################################
        # Counting selected non-junk tubes
        total_nonjunk_tubes = 0
        for keys, values in self.nonjunk_tubes.iteritems():
            total_nonjunk_tubes += len(values)
        # print 'Total nonjunk_tubes: %d' % (total_nonjunk_tubes)
        # print self.nonjunk_tubes



    ###################################################################### CHECK AA DEIMMUNIZING #########
    #
    # This method creates a deimmunizing list of flags (0 or 1) for all AAs at all positions.
    # The list is then used in junkFilter method.
    #
    def tube_aa_deimmunizing(self, min_epi_del=1, introduce_epitope=0, profile_threshold=5):
        AAs = "ACDEFGHIKLMNPQRSTVWY"
        
        for pos in range(len(self.wt_seq)):
            for aa in AAs:
                variant_seq_list = list(self.wt_seq)
                if (len(self.wt_seq)-pos) > 8: # Ignores last 8 AAs in the sequence because we cannot get their epitope scores
                    variant_seq_list[pos] = aa
                    variant_seq = "".join(variant_seq_list)
                    wt_allele_hits = self.profiles.num_hits(self.wt_seq, profile_threshold)
                    variant_allele_hits = self.profiles.num_hits(variant_seq, profile_threshold)
                    if (wt_allele_hits - variant_allele_hits) >= min_epi_del: # If it deletes the minimum required number, we check further if it introduces any epitope
                        sound = True
                        if pos >=8:
                            for q in range((pos-8), (pos+1)):
                                wt_pep_hits = self.profiles.peptide_hits(self.wt_seq[q:q+9], profile_threshold)
                                variant_pep_hits = self.profiles.peptide_hits(variant_seq[q:q+9], profile_threshold)
                                if (wt_pep_hits - variant_pep_hits) < 0:
                                    sound = False # The hpm introduces an epitope
                        else:
                            for q in range(0, (pos+1)):
                                wt_pep_hits = self.profiles.peptide_hits(self.wt_seq[q:q+9], profile_threshold)
                                variant_pep_hits = self.profiles.peptide_hits(variant_seq[q:q+9], profile_threshold)
                                if (wt_pep_hits - variant_pep_hits) < 0:
                                    sound = False # The hpm introduces an epitope

                        if introduce_epitope == 1: # Bypassing, i.e., even if it introduces new epitope we include that choice
                            sound = True
                            
                        if sound == True: self.aa_pos_deimm[(pos, aa)] = 1
                        else: self.aa_pos_deimm[(pos, aa)] = 0
                    else: self.aa_pos_deimm[(pos, aa)] = 0 # It does not delete required number of epitopes
                else: # If choiced positions are the last 8 positions of the sequence, we return True just for the wildtype AA
                    if variant_seq_list[pos] == aa: self.aa_pos_deimm[(pos, aa)] = 0
                    else: self.aa_pos_deimm[(pos, aa)] = 0



    ################################################################################################ RENAME TUBES ###
    #
    # This is the final step for preprocessing tubes.
    # Renaming tubes so that they can be used further for calculating potentials.
    #
    def renameTubes(self, non_mutable_sites = []):
        print ('Renaming Tubes...')
        temp_pos_choices = {}
        allowed_mutated_pos_1 = []
        #updates
        for p in self.thres_filtered_seq_choices:
            if p[0] not in temp_pos_choices:
                temp_pos_choices[p[0]] = 1
            else:
                temp_pos_choices[p[0]] += 1

        for p in temp_pos_choices:
            if temp_pos_choices[p] > 1:
                allowed_mutated_pos_1.append(p)

        allowed_mutated_pos_2 = [i for i in range(len(self.wt_seq)) if i not in non_mutable_sites]
        allowed_mutated_pos = list(set(allowed_mutated_pos_1 + allowed_mutated_pos_2))
        print (allowed_mutated_pos)
    
        ################################
        # Tubes coding for wildtype residue are replaced by single letter tube code
        # The choices are stored in variable self.possible_tubechoices
        total_selected_tubes = 0
        for keys, values in self.nonjunk_tubes.iteritems():
            for i in range(0, len(values)):
                if keys in allowed_mutated_pos:
                    if self.non_redundant_tubes[values[i]][0] == self.wt_seq[keys] and len(self.non_redundant_tubes[values[i]]) == 1:
                        self.possible_tubechoices.append([keys, self.non_redundant_tubes[values[i]][0]])
                    else:
                        self.possible_tubechoices.append([keys, values[i]])
                elif self.non_redundant_tubes[values[i]][0] == self.wt_seq[keys] and len(self.non_redundant_tubes[values[i]]) == 1:
                    self.possible_tubechoices.append([keys, self.non_redundant_tubes[values[i]][0]])


        ################################
        # Final list of selected tubes stored as dictionary
        # Keys = Residue positions, Values = Tube choices
        for i in range(len(self.possible_tubechoices)):
            if self.possible_tubechoices[i][0] in self.selected_tubes:
                self.selected_tubes[self.possible_tubechoices[i][0]].append(self.possible_tubechoices[i][1])
            else:
                self.selected_tubes[self.possible_tubechoices[i][0]] = [self.possible_tubechoices[i][1]]
        
        print (self.selected_tubes)
        print ('Total singleton TUBE choices: %d' % (len(self.selected_tubes)))




    ################################################################################## TUBE ONEBODY SCORES ###
    #
    # Calculating onebody tubescores
    # Onebody AA scores are required for calculation
    # The scores can be normalized based upon their size (default = True).
    #
    def onebody_tube(self, normalization = True):
        print ('Implementing onebody tube...')
        for keys,values in self.selected_tubes.iteritems():
            for i in range(len(values)):
                if values[i] == self.wt_seq[keys] and len(values[i]) == 1:
                    aa_coded = [self.wt_seq[keys]]
                else:
                    #aa_coded = self.non_redundant_tubes[values[i]]
                    aa_coded = list(set(self.non_redundant_tubes[values[i]])) # Changed for non-degenerate counting on Dec 23 2014
                
                aa_count = {}
                for m in set(aa_coded): aa_count[m] = float(aa_coded.count(m))
                tube_score = 0.0
                tube_score_list = []
                for aa,count in aa_count.iteritems():
                    # Check if normalization is required
                    if normalization == False: norm = 1
                    else: norm = len(aa_coded) / float(count)
                    # Calculating onebody scores
                    if (keys, aa, 0) in self.onebody_score:
                        cons = self.onebody_score[(keys, aa, 0)]/norm
                    else:
                        if self.CLEVER_flag: cons = 0.0 # treated differently for clever scores
                        else: cons = (1*self.penalty)/norm
                    
                    tube_score += cons
                    for nt in range(int(count)): tube_score_list.append(cons*norm)
                self.onebody_tubescores[keys, values[i], 0] = tube_score
                self.onebody_tube_scoreslist[keys, values[i], 0] = tube_score_list
                del aa_count
    
        print ('Length of onebody_tubescores: %d' % (len(self.onebody_tubescores)))
        



    ################################################################################## TUBE TWOBODY SCORES ###
    #
    # Calculating twobody tubescores
    # Onebody and twobody AA scores are required for calculation.
    # Also required is the possible_pairs list.
    # The scores can be normalized based upon their size (default = True).
    #
    def twobody_tube(self, normalization = True):
        print ('Implementing twobody tube...')
        print ('self.possible_pairs', self.possible_pairs, len(self.possible_pairs))
        for keys_i,values_i in self.selected_tubes.iteritems():
            for i in range(len(values_i)):
                if values_i[i] == self.wt_seq[keys_i] and len(values_i[i]) == 1:
                    aa_coded_i = [self.wt_seq[keys_i]]
                else:
                    #aa_coded_i = self.non_redundant_tubes[values_i[i]] # Changed for non-degenerate counting on Dec 23 2014
                    aa_coded_i = list(set(self.non_redundant_tubes[values_i[i]]))
                aa_count_i = {}
                for m in set(aa_coded_i): aa_count_i[m] = float(aa_coded_i.count(m))
                
                for keys_j,values_j in self.selected_tubes.iteritems():
                    # if they are in coupled list from MSA
                    
                    if (keys_i < keys_j) and ((keys_i, keys_j) in self.possible_pairs):
                        for j in range(len(values_j)):
                            if values_j[j] == self.wt_seq[keys_j] and len(values_j[j]) == 1:
                                aa_coded_j = [self.wt_seq[keys_j]]
                            else:
                                #aa_coded_j = self.non_redundant_tubes[values_j[j]] # Changed for non-degenerate counting on Dec 23 2014
                                aa_coded_j = list(set(self.non_redundant_tubes[values_j[j]]))
                            aa_count_j = {}
                            for m in set(aa_coded_j): aa_count_j[m] = float(aa_coded_j.count(m))
    
                            tube_score = 0.0
                            for aa_i, count_i in aa_count_i.iteritems():
                                for aa_j, count_j in aa_count_j.iteritems():
                                
                                    # Check if normalization is required
                                    if normalization == False: norm_a = 1; norm_b = 1
                                    else: norm_a = len(aa_coded_i)/float(count_i); norm_b = len(aa_coded_j)/float(count_j)
                                    
                                    # Calculating twobody scores
                                    if (keys_i, aa_i, 0, keys_j, aa_j, 0) in self.twobody_score:
                                        cov = (self.twobody_score[(keys_i, aa_i, 0, keys_j, aa_j, 0)])/(norm_a*norm_b)
                                    else:
                                        if (keys_i, aa_i, 0) in self.onebody_score and (keys_j, aa_j, 0) in self.onebody_score:
                                            if self.CLEVER_flag: cov = 0.0 # treated differently for clever scores
                                            else: cov = ((2*self.penalty) - self.onebody_score[(keys_i, aa_i, 0)] - self.onebody_score[(keys_j, aa_j, 0)])/(norm_a*norm_b)
                                        else:
                                            cov = (2*self.penalty)/(norm_a*norm_b)
                            
                                    tube_score += cov
                        
                            self.twobody_tubescores[keys_i, values_i[i], 0, keys_j, values_j[j], 0] = tube_score
                            del aa_count_j
                del aa_count_i
        
        print ('Length of twobody_tubescores: %d' % (len(self.twobody_tubescores)))